### ISSUE TITLE
Bug in crab report --recovery options

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABClient#4736] opened 2018-01-24 14:38 UTC
- [ ] crab report --recovery='failed' - fixed in https://github.com/dmwm/CRABClient/issues/5326
and
- [x] crab report --recovery='notPublished' - fixed in https://github.com/dmwm/CRABServer/issues/5631
do not produce the corresponding json file ("failedLumis.json" and "notPublishedLumis.json") as for [documentation](https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3Commands#crab_report).

**Comment by belforte** [comment] 2018-01-29 11:19
I ran the client with pdb and figured out that the problem is server side,
From line 111 of report.py lumisToProcessPerJob is a list of empty dictionaries.
So the client does not know what was supposed to be processed and can't creare the list of what is to be recovered.
Refs:
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/report.py#L111
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/report.py#L281-L333

**Comment by belforte** [comment] 2018-01-29 11:20
we should anyhow keep this open until server side has been understood, possibly fixed and result verified in crab report

**Comment by belforte** [comment] 2018-01-29 17:38
Nopw. List of lumis to be processed should be retrieved from webdir. More investigation is needed.

**Comment by belforte** [comment] 2018-01-29 22:57
I was testing the code on this task which was reported y a user last week:
https://cmsweb.cern.ch/crabserver/ui/task/180121_124727%3Agsfs_crab_EPOS_MinBias_RECODEBUG_XeXe_9_4_Full

where the recovery lumimasks are missing as in the initial issue comment.
Eventually I found that this is because the task used `config.Data.splitting = 'FileBased'` and in thie case the `run_and_lumis.tar.gz` has no info on the input lumi list for each file
Basically recovery=notPublished works only with splitting by lumi.
Of course client could be modified to generare the recovery mask using the list of lumis in each file from DBS etc. I  vaguely remember a discussion on this with past developers (Andres ? Emilis ?).
Anyhow I think the best is to document the situation. Users can use lumimask algebra starting from DBS as already documented to create a lumimaks in this case.

@lecriste plese make sure that documentation and crab report --help and output report this fact.

**Comment by belforte** [comment] 2024-01-17 14:42
@mapellidario can you easily and quickly check if this is overridden by new crab recovery and close ? If it takes more than 30min, let's close anyhow. It is 5 years old and I have not heard anybody complaining

**Comment by belforte** [comment] 2024-08-23 10:32
all fixed now !

**Closed by belforte** 2024-08-23 10:32 UTC
Labels: Low Priority, Documentation
