### ISSUE TITLE
dryrun fails due to files not being available from the S3 server

### ISSUE THREAD

**Issue by simonepigazzini** [dmwm/CRABClient#5064] opened 2021-08-17 09:01 UTC
After the switch to the S3 platform to store the jobs sandbox I've noticed that running `crab submit --dryrun` (or the equivalent using the CRABClient) leads to a failure caused by issues with downloading the tarball from S3. It looks like there is some lag between when the job is uploaded to the scheduler and when the tarball is actually available from S3.

I got a very dirty [fix] running by manipulating the executeTestRun method of the submit command. Is this a known problem that will be fixed in future crab releases?

Furthermore it would be nice to have access to the splitting information from the python client rather than having to resort to parse stdout.

simone

[fix]: https://gitlab.cern.ch/spigazzi/PhiSym/-/blob/automation_dev/EcalCalibAlgos/scripts/phisym_crab_submit.py#L40

**Comment by belforte** [comment] 2021-08-17 09:59
thanks @simonepigazzini for reporting and investigating .
This was also noticed by another user last week and a fix is now in the master branch
https://github.com/dmwm/CRABServer/issues/6706
But I had thought this to happen rarely so have not created a hot patch for current version.
New CRAB version with this fix will go in production as part of "CRAB ready for CMSSW_12_*" which is still a few weeks away.
Let me know if you believe that it is more urgent.

OTOH I do not understand what exactly you refer to in the last part, `dryrun` is supposed to be used interactively. Also it has known shortcomings and I'd rather have people use automatic splitting or `crab preparelocal` to run one example job in case one wants to e.g. check memory usage. The person who developer `dryryun` left long ago and I can't commit to maintain that code (as well). I need to reduce the number of CRAB options and features.

**Comment by simonepigazzini** [comment] 2021-08-17 13:07
Hi Stefano,

it's not so urgent, thanks for patching it already.

Concerning the second request my point is that from dryrun one can retrieve the number of jobs produced by the task (in particular when running with automatic splitting). This at times is a useful information (for instance to save logs beyond the natural crab task lifetime).

**Comment by belforte** [comment] 2021-08-17 14:20
user-driven splitting and automatic splitting behave very differently and the number of jobs generated by the latter is actually dynamic as spliting gets finer as finer when things are retried.
But IIUC you would like to see in dryrun case the number of jobs created.
That is not simple, since it is not part of the information available in the CRAB database at that time,
outputs like [1] below come from information created when things start to run on the HTCondor schedds,
while dryrun processing stops before that.
I can see why you'd like this info, but it is not a trivial change and affects code both in Server and Client.

Anyhow I am taking a note to add this in case I come up with some idea on how to do it w/o inordinate amount of work: https://github.com/dmwm/CRABClient/issues/5065


[1]
```
Status on the scheduler:	SUBMITTED

Jobs status:                    finished     		 97.2% ( 972/1000)
				transferring 		  2.8% (  28/1000)

```

**Comment by belforte** [comment] 2021-08-17 14:21
closing since the issue is a duplicate of  dmwm/CRABServer#6706 and #5060

**Closed by belforte** 2021-08-17 14:21 UTC
Labels: question
