### ISSUE TITLE
investigate weird CachefileNotFoundException

### ISSUE THREAD

**Issue by qunox** [dmwm/CRABClient#4255] opened 2014-08-27 12:42 UTC
> ERROR 2014-08-27 09:30:19,653:   Caught exception
> Traceback (most recent call last):
>   File "/data/CRABClient/bin/crab", line 196, in <module>
>     client()
>   File "/data/CRABClient/bin/crab", line 181, in __call__
>     self.cmd = sub_cmd(self.logger, args[1:])
>   File "/data/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line
> 211, in __init__
>     self.loadLocalCache()
>   File "/data/CRABClient/src/python/CRABClient/Commands/SubCommand.py", line
> 312, in loadLocalCache
>     self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
>   File "/data/CRABClient/src/python/CRABClient/client_utilities.py", line
> 263, in loadCache
>     raise CachefileNotFoundException( msg )
> CachefileNotFoundException: Cannot find .requestcache file inside the
> working directory for task crab_tutorial_MC_generation_test220140827 92922
> ERROR: TypeError: expected a character buffer object
> ERROR: TypeError: expected a character buffer object
>
>     Please email hn-cms-computing-tools@cern.ch for support and include the
> last lines of crab.log.
>
>     Please email hn-cms-computing-tools@cern.ch for support and include the
> last lines of crab.log.
>     Client Version: development
>     Client Version: development
> Unhandled Exception!
> expected a character buffer object
> Traceback (most recent call last):
>   File "/data/CRABClient/bin/crab", line 225, in <module>
>     reason =
> reason.replace(tmpmsg,tmpmsg.replace(parname,parameters_mapping['on-server'][parname]['config']))
> TypeError: expected a character buffer object
>

**Comment by AndresTanasijczuk** [comment] 2015-04-21 16:36
The error "TypeError: expected a character buffer object" was caused by the fact that parameters_mapping['on-server'][parname]['config'] was None (instead of a string). This was fixed already. About the CachefileNotFoundException, why would it be "weird"? Because the project directory name had a space in it? Currenlty there is an error message for this:
$ crab status -d crab_test_ignoreAuto_True_edm\ 11
Working directory for task crab_test_ignoreAuto_True_edm 11 not found

So I am closing this issue as I think there is nothing else to do for it.

**Closed by AndresTanasijczuk** 2015-04-21 16:36 UTC
