### ISSUE TITLE
Implement invalidation of files/datasets in DBS

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4387] opened 2015-01-29 12:08 UTC
Current twiki with instructions for users on how to invalidate a dataset (or individual files of a dataset): https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCrabForPublication?redirectedfrom=CMS.SWGuideCrabForPublication#Invalidate_a_dataset_in_DBS
Scripts from DBS3: https://github.com/dmwm/DBS/tree/master/Client/utils/DataOpsScripts

**Comment by belforte** [comment] 2015-09-14 12:42
duplicate of #4551

**Closed by belforte** 2015-09-14 12:42 UTC
Labels: enhancement, Support
