### ISSUE TITLE
Import CMSSW config in an isolated way

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABClient#4248] opened 2014-08-25 15:03 UTC
Regardless of where the client API goes, the way we import CMSSW configurations needs to change. The big problem is that CMSSW configs aren't idempotent. See the following traceback:

```
./bulkcrab.py 
No handlers could be found for logger "CRAB3"
 Taus:  cms.InputTag("hpsPFTauProducer") -> cms.InputTag("hpsPFTauProducer")

The btaginfo below will be written to the jet collection in the PATtuple (default is all, see PatAlgos/PhysicsTools/python/tools/jetTools.py)
impactParameterTagInfos
secondaryVertexTagInfos

The bdiscriminators below will be written to the jet collection in the PATtuple (default is all, see PatAlgos/PhysicsTools/python/tools/jetTools.py)
jetBProbabilityBJetTags
jetProbabilityBJetTags
trackCountingHighPurBJetTags
trackCountingHighEffBJetTags
simpleSecondaryVertexHighEffBJetTags
simpleSecondaryVertexHighPurBJetTags
combinedSecondaryVertexBJetTags
140825_003416_crab3test-1:meloam_crab_ra2taupat_bNAI9
 Taus:  cms.InputTag("hpsPFTauProducer") -> cms.InputTag("hpsPFTauProducer")
Traceback (most recent call last):
  File "./bulkcrab.py", line 77, in <module>
    main()
  File "./bulkcrab.py", line 58, in main
    print oneTask.submit()
  File "/gpfs22/home/meloam/CRABAPI/CRABAPI/Task.py", line 24, in submit
    return submitCommand()
  File "/gpfs22/home/meloam/CRABAPI/CRABClient/src/python/CRABClient/Commands/submit.py", line 116, in __call__
    inputfiles, jobconfig, isbchecksum = plugjobtype.run(configreq)
  File "/gpfs22/home/meloam/CRABAPI/CRABClient/src/python/CRABClient/JobType/Analysis.py", line 65, in run
    userConfig=self.config.JobType.psetName)
  File "/gpfs22/home/meloam/CRABAPI/CRABClient/src/python/CRABClient/JobType/CMSSWConfig.py", line 48, in __init__
    modPath[1],  modPath[2])
  File "patProd_mc.py", line 207, in <module>
    process.eleIsoSequence = setupPFElectronIso(process, 'gsfElectrons')
  File "/gpfs21/scratch/meloam/SUSHyFT-Scripts/checkouts/pat/python/CommonTools/ParticleFlow/Tools/pfIsolation.py", line 129, in setupPFElectronIso
    return setupPFIso( process, electronCollection, 'Electron', newpostfix, postfix, runPF2PAT)
  File "/gpfs21/scratch/meloam/SUSHyFT-Scripts/checkouts/pat/python/CommonTools/ParticleFlow/Tools/pfIsolation.py", line 50, in setupPFIso
    ga('pf{lepton}IsolationSequence'.format(lepton=particleName))  
  File "/gpfs21/scratch/meloam/SUSHyFT-Scripts/checkouts/pat/python/CommonTools/ParticleFlow/Tools/pfIsolation.py", line 9, in fun
    return getattr(process, name+postfix)
AttributeError: 'Process' object has no attribute 'pfElectronIsolationSequence'
```

The line ```meloam_crab_ra2taupat_bNAI9``` is a request ID for a successful task submitted, the subsequent lines are an attempt to submit the same configuration with a different input dataset. The problem is that CMSSWConfig.py pulls the config into the global namespace, and CMSSW's configs don't like to play that way.

**Comment by belforte** [comment] 2016-02-03 08:38
duplicate of https://github.com/dmwm/CRABClient/issues/4493

**Closed by belforte** 2016-02-03 08:38 UTC
